### ISSUE TITLE
How to keep !important for a css attribute?

### ISSUE THREAD

**Issue by nguyenap** [cure53/DOMPurify#877] opened 2023-11-16 10:32 UTC
I just have a question.
In [demos/hooks-sanitize-css-demo.html](https://github.com/cure53/DOMPurify/blob/main/demos/hooks-sanitize-css-demo.html); i changed color with !important attr ;
```
<style>
                big {
                    list-style: url(https://leaking.via/css-list-style);
                    list-style-image: url(https://leaking.via/css-list-style-image);
                    background: url(https://leaking.via/css-background);
                    background-image: url(https://leaking.via/css-background-image);
                    border-image: url(https://leaking.via/css-border-image);
                    border-image-source: url(https://leaking.via/css-border-image-source);
                    shape-outside: url(https://leaking.via/css-shape-outside);
                    cursor: url(https://leaking.via/css-cursor), auto;
                    color:red !important;
                }
 </style>
```
I checked  in the 'uponSanitizeElement ' hook event, but  The `!important`  has been removed the node value.
<img width="770" alt="image" src="https://github.com/cure53/DOMPurify/assets/18488698/90f239e0-5b1c-4c4a-818a-52f1262b2328">

**Comment by cure53** [comment] 2023-11-17 14:46
Hmm, I think you need to use special magic for this:

https://stackoverflow.com/questions/13765266/how-can-one-set-a-css-property-with-the-important-flag-via-the-dom

**Comment by cure53** [comment] 2023-11-18 12:17
Closing this as likely not our bug.

**Closed by cure53** 2023-11-18 12:16 UTC

**Comment by nguyenap** [comment] 2023-11-20 01:54
Thank you for your reply, I'll look into it more but have no other ideas as this "!important" is being left out of the sanitize function and we can't determine which css attribute it goes with .

**Comment by cure53** [comment] 2023-11-20 07:07
Maybe it is possible that the browser removes it when processing the markup internally? At least from what I can see, we have no logic in DOMPurify that does anything with that directive.

I tested, and it looks like DOMPurify indeed leaves the important declaration untouched: 

```javascript
DOMPurify.sanitize('ABC<style>big {color:red !important;}</style><big>HELLO</big>')
"ABC<style>big {color:red !important;}</style><big>HELLO</big>" 
```
So, my guess is, the problem is caused by something else?
