### ISSUE TITLE
DOMPurify remove script tag even if script tag allowed

### ISSUE THREAD

**Issue by OmkarSingh7** [cure53/DOMPurify#711] opened 2022-08-18 09:16 UTC
> DOMPurify remove script tag even if script tag allowed

### Background & Context

DOMPurify remove script tag if it contains HTML tags, for example following script tag will be removed!

#### Input

    <h1>hello</h1>
    <script type="text/javascript">
        var tooltip = "<p class='abc' id='pqr'>My Message</p>";
        $("#selector").html(tooltip);
    </script>   

#### Given output

    <h1>hello</h1>

#### Expected output

    <h1>hello</h1>
    <script type="text/javascript">
        var tooltip = "<p class='abc' id='pqr'>My Message</p>";
        $("#selector").html(tooltip);
    </script>   

Can you please explain why this is happening and what is the solution for the same? Thanks

**Comment by cure53** [comment] 2022-08-23 06:50
The problem here is that you have a closing tag (the part with the `My Message</p>`) in your script tag - and for mXSS protection, DOMPurify removes those.

I am wondering, this does not look like user controlled content, is sanitization even needed here?

**Comment by cure53** [comment] 2022-08-23 08:43
Then why not sanitize the message itself rather than the whole template? It's cheaper, less error prone, and appears like the way to go rather - especially compared to permitting script elements, no?

**Comment by OmkarSingh7** [comment] 2022-08-23 09:01
The main problem is that this entire script tag in part of ajax response, and i am actually sanitizing that response.

**Comment by cure53** [comment] 2022-08-23 09:03
But that is broken by design, no? How would sanitizing fix anything here?

**Comment by OmkarSingh7** [comment] 2022-08-23 09:07
Yes this is design flow, I was just wanted to know is there any workaround or any config available for the same. In the ultimate solution to remove HTML all together from script.

**Comment by cure53** [comment] 2022-08-23 09:13
I guess the best way would be to get a hand on the message and sanitize it before it is being added to the DOM, like, changing the response to this:

`$("#selector").html(DOMPurify.sanitize(tooltip));`

**Comment by OmkarSingh7** [comment] 2022-08-23 09:22
Yes, this is what i am already doing, my issue related to that closing html tag `</p>` in this case as you explain earlier, I fix this by removing all html from script tag. Thanks for the response.

**Closed** 2022-08-23 09:44 UTC
