### ISSUE TITLE
[bug] - Build error in angular app

### ISSUE THREAD

**Issue by mathiasdeoliveira** [cure53/DOMPurify#895] opened 2024-01-04 13:14 UTC
**[bug] - Build error in angular app since your last version 3.0.7**

Error: export 'sanitize' (imported as 'DOMPurify') was not found in 'dompurify' (possible exports: default)

### Background & Context

We use your library with Angular version 15 and dompurify import in non-fixed mode. 

_package.json_
`"dompurify: "^3.0.6",`

and import like this into the typescript file

`import * as DOMPurify from 'dompurify';`

**Temporary solution :** 

use fixed version "dompurify: "3.0.6"

**Comment by cure53** [comment] 2024-01-04 13:19
Oha, we didnÄt change much that might impact how to import the library, do you have more info per chance?

**Comment by cure53** [comment] 2024-01-04 13:21
Maybe the changes done in early November are the culprit? cc @ssi02014 

https://github.com/cure53/DOMPurify/compare/3.0.6...3.0.7

**Comment by Justxs** [comment] 2024-01-04 14:18
I have same issue using React

**Comment by pauly92** [comment] 2024-01-04 14:19
I have the same using LIT.

This is the error message i get:

Import "sanitize" will always be undefined because there is no matching export in "../../node_modules/dompurify/dist/purify.es.mjs" [import-is-undefined]

**Comment by cure53** [comment] 2024-01-04 14:23
@ssi02014 If possible, please have a look. I am pretty sure this is because of the changes in November:

https://github.com/cure53/DOMPurify/pull/874#issuecomment-1803975568

**Comment by CaptainGlac1er** [comment] 2024-01-04 15:45
Also getting this error once my app updated from 3.0.6 -> 3.0.7

**Comment by ssi02014** [comment] 2024-01-04 15:46
@cure53 
Until v3.0.6, we loaded "dist/purify.js" in `umd` format, but since v3.0.7, we load "dist/purify.es.mjs" in `esm` format, which seems to cause related issues.

Currently, purfiy is exporting via `export default createDOMPurify();` so importing with `import DOMPurify from 'dompurify'"`doesn't seem to cause the issue.

**Comment by CaptainGlac1er** [comment] 2024-01-04 15:48
@ssi02014 I have the issue importing with `import * as DOMPurify from 'dompurify';`

**Comment by ssi02014** [comment] 2024-01-04 15:51
```tsx
import DOMPurify from 'dompurify'"
```
Can you tell if you're getting an error if you proceed as above?

**Comment by cure53** [comment] 2024-01-04 15:56
> ```tsx
> import DOMPurify from 'dompurify'
> ```
> 
> Do you get an error if you do the above?

Either way we need a fix that makes things work for everyone who uses the ways described above (i.e. not break things). I am happy to release a 3.0.8 once this is sorted. I cannot do much here myself, but I presume it's a quick fix after all :smile:

**Comment by cure53** [comment] 2024-01-04 17:09
@mathiasdeoliveira @Justxs @pauly92 @CaptainGlac1er This PR should fix the issue, please check if possible if this does the trick indeed. If so, we will release 3.0.8 tomorrow. Thanks @ssi02014 for the super-fast reaction!

**Comment by CaptainGlac1er** [comment] 2024-01-04 20:23
@ssi02014 this is probably why I didn't use that approach. 
![image](https://github.com/cure53/DOMPurify/assets/9340895/cd019d43-8360-4100-a63b-564ea826395f)

**Comment by CaptainGlac1er** [comment] 2024-01-04 20:23
@ssi02014 this is probably why I didn't use that approach. 
![image](https://github.com/cure53/DOMPurify/assets/9340895/ce47a582-524c-41fc-beb0-6fd754256584)

**Comment by CaptainGlac1er** [comment] 2024-01-04 20:32
@cure53 also ccing you on this ^

**Comment by reduckted** [comment] 2024-01-05 01:24
This might be helpful. _Are The Types Wrong?_ is reporting that the ESM export is "Masquerading as CJS".

https://arethetypeswrong.github.io/?p=dompurify%403.0.7

```
┌───────────────────┬────────────────────────┬──────────────────────────┐
│                   │ "dompurify"            │ "dompurify/package.json" │
├───────────────────┼────────────────────────┼──────────────────────────┤
│ node10            │ 🟢                     │ 🟢 (JSON)                │
├───────────────────┼────────────────────────┼──────────────────────────┤
│ node16 (from CJS) │ 🟢 (CJS)               │ 🟢 (JSON)                │
├───────────────────┼────────────────────────┼──────────────────────────┤
│ node16 (from ESM) │ 🎭 Masquerading as CJS │ 🟢 (JSON)                │
├───────────────────┼────────────────────────┼──────────────────────────┤
│ bundler           │ 🟢                     │ 🟢 (JSON)                │
└───────────────────┴────────────────────────┴──────────────────────────┘
```

**Comment by ssi02014** [comment] 2024-01-05 01:51
`"conditional export"` was applied in v3.0.7, but I worked on reverting it back.
I expect this will be fixed.

https://github.com/cure53/DOMPurify/pull/896/files

**Comment by ghiscoding** [comment] 2024-01-05 04:13
I have the same problem in Angular with `allowSyntheticDefaultImports` enabled. 

```sh
Slickgrid/node_modules/@types/dompurify/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag      

7 import DOMPurify from 'dompurify';
         ~~~~~~~~~

  node_modules/@types/dompurify/index.d.ts:4:1
    4 export = DOMPurify;
      ~~~~~~~~~~~~~~~~~~~
    This module is declared with 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.
```
if I remove `@types/dompurify` then my build works but then I get lint errors in my editor 
`Could not find a declaration file for module 'dompurify'.`

So I wonder if there's a problem with `@types/dompurify` instead of the actual release? Because that type only got updated a month ago so it doesn't follow the new release which was just couple days ago, shouldn't the type also be updated and that might fix the issue?

**Comment by cure53** [comment] 2024-01-05 08:53
Thanks, @ghiscoding and @ssi02014 - I am unsure now, shall we go with the given PR or file a PR against `@types/dompurify`?

**Comment by dkocich** [comment] 2024-01-05 11:46
i have issue in react v18 codebase (CRA) - webpack wont build; i have only available "@types/dompurify": "3.0.5",

**Comment by ghiscoding** [comment] 2024-01-05 14:19
> Thanks, @ghiscoding and @ssi02014 - I am unsure now, shall we go with the given PR or file a PR against `@types/dompurify`?

The revert of all the exports will probably (hopefully) help, I think that I would give that a try so that we can still `import * as dompurify from 'dompurify` in Angular

**Comment by cure53** [comment] 2024-01-05 16:44
This release should fix it: https://github.com/cure53/DOMPurify/releases/tag/3.0.8

**Comment by ghiscoding** [comment] 2024-01-05 18:20
I also confirmed that my CI build is now working, this issue could probably be closed since it was for Angular and I just confirmed that it works in Angular. Thanks for this great project and the quick turnaround with a fix 👍🏻

**Comment by cure53** [comment] 2024-01-05 21:00
Awesome, phew :heart: Glad to hear it worked!

**Closed by cure53** 2024-01-05 21:00 UTC

**Comment by luizzappa** [comment] 2024-11-23 20:59
This issue returned in version `3.0.9` and later. Currently I had to force version `3.0.8` to work with webpack
