### ISSUE TITLE
Enable property attribute on meta tags

### ISSUE THREAD

**Issue by elias94** [cure53/DOMPurify#524] opened 2021-03-14 04:33 UTC
### Background & Context

I'm trying to purify a HTML document with `meta` tags with this configuration
```javascript
const _window = new JSDOM('').window
const DOMPurify = createDOMPurify(_window)

// HTML containst meta tags in the head
const cleanHTML = DOMPurify.sanitize(html, {
  WHOLE_DOCUMENT: true,
  ADD_TAGS: ['head', 'meta'],
  ADD_ATTR: ['content', 'property'],
})
```

### Bug

Unable to maintain `property` attribute on `meta` tags

#### Input

[Example article](https://newrepublic.com/article/73666/toward-new-alexandria) for html

```html
<meta data-react-helmet="true" property="og:url" content="https://newrepublic.com/article/73666/toward-new-alexandria"/>
```

#### Given output

```html
<meta data-react-helmet="true" content="https://newrepublic.com/article/73666/toward-new-alexandria"/>
```

#### Expected output

```html
<meta data-react-helmet="true" property="og:url" content="https://newrepublic.com/article/73666/toward-new-alexandria"/>
```

P.S.
No discussion section so I had to post it here.

**Comment by cure53** [comment] 2021-03-14 09:47
Heya, I have a feeling that this might be caused by he clobbering protection. Have you tried this setting?

`var clean = DOMPurify.sanitize(dirty, {SANITIZE_DOM: false});`

**Comment by elias94** [comment] 2021-03-14 11:37
Tried (alone and not) but same output. Here is the full code

```javascript
axios.get('https://newrepublic.com/article/73666/toward-new-alexandria').then((response) => {
  const html = response.data

  const _window = new JSDOM('').window
  const DOMPurify = createDOMPurify(_window)

  const cleanHTML = DOMPurify.sanitize(html, {
    WHOLE_DOCUMENT: true,
    SANITIZE_DOM: false,
    ADD_TAGS: ['head', 'meta'],
    ADD_ATTR: ['content', 'property'],
  })

  console.log(cleanHTML)
}).catch((e) => {
  console.error(e)
})
```

**Comment by cure53** [comment] 2021-03-14 12:41
Ooooh, I found out what the problem is :) DOMPurify thinks, `og:url` is some evil URL scheme. Thy this:

```javascript
const cleanHTML = DOMPurify.sanitize('<meta data-react-helmet="true" property="og:url" content="https://newrepublic.com/article/73666/toward-new-alexandria"/>', 
{
  WHOLE_DOCUMENT: true,
  ADD_URI_SAFE_ATTR: ['property'],
  ADD_TAGS: ['head', 'meta'],
  ADD_ATTR: ['content', 'property'],
})

console.log(cleanHTML)
```

**Comment by cure53** [comment] 2021-03-14 15:31
Closing this, assuming the issue was addressed successfully.

**Closed by cure53** 2021-03-14 15:31 UTC

**Comment by elias94** [comment] 2021-03-14 21:44
Perfect, thanks!
