### ISSUE TITLE
<style> tag removed if it's the first tag

### ISSUE THREAD

**Issue by dgrad** [cure53/DOMPurify#128] opened 2015-11-29 23:01 UTC
Running this works as expected:
```javascript
var testHtml = '<span>1</span><style type="text/css">span { z-index: 1; }</style><span>2</span>';
console.log(dompurify.sanitize(testHtml));
// <span>1</span><style type="text/css">span { z-index: 1; }</style><span>2</span>
```

But this simply strips the `<script>` tag:
```javascript
var testHtml = '<style type="text/css">span { z-index: 1; }</style><span>1</span><span>2</span>';
console.log(dompurify.sanitize(testHtml));
// <span>1</span><span>2</span>
```

**Comment by cure53** [comment] 2015-11-30 10:35
Hi @dgrad!

This is because browsers move a `<style>` element that is positioned at the very beginning of the body into the header section of the DOM. This also holds for a bunch of other elements. The problem is known and we have a workaround for that, which is described here:

https://github.com/cure53/DOMPurify/issues/37

If that already helps, feel to close the issue, if not, please let us know :)

**Comment by dgrad** [comment] 2015-12-02 03:29
Thanks, that explains things.

**Closed** 2015-12-02 03:29 UTC
