### ISSUE TITLE
Failed to execute 'invoke' on 'CreateHTMLCallback': The provided callback is no longer runnable.

### ISSUE THREAD

**Issue by jlowcs** [cure53/DOMPurify#529] opened 2021-03-24 22:08 UTC
### Background & Context

We are using dompurify to sanitize our HTML before injecting it.

### Bug

We have that error being reported for some of our users, apparently mostly when running from SamsungBrowsers on Android 10/11.

Stacktrace example (from Airbrake):
![image](https://user-images.githubusercontent.com/3777724/112389773-959e7c80-8cf5-11eb-8032-77104f17b2cb.png)

user agent example: `Mozilla/5.0 (Linux; Android 11; SAMSUNG SM-G998B) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/13.2 Chrome/83.0.4103.106 Mobile Safari/537.36`

(The browser is identified as supported by dompurify).

I wasn't able to reproduce it on browserstack though...

Any insight as to what's happening?

**Comment by cure53** [comment] 2021-03-25 12:47
Hmm, I don't see that in any of our tests. @koto potentially anything with TT on Chrome 83?

**Comment by koto** [comment] 2021-03-25 12:54
If this only surfaces when setting the breakpoints in Chrome Developer Tools, it's probably https://bugs.chromium.org/p/chromium/issues/detail?id=1131368. Is the error not there when the code runs normally?

**Comment by jlowcs** [comment] 2021-03-25 13:33
These errors are being reported to Airbrake. They are coming from our users, and apparently are mostly happening on Samsung devices (using the Samsung browser). So this probably has nothing to do with breakpoints.

That being said, I wasn't able to reproduce it on browserstack or on my own Samsung device. So I don't know what specific circumstances are needed for that error to happen.

**Comment by cure53** [comment] 2021-03-25 13:39
Do you happen to know which version of DOMPurify is being used here?

**Comment by koto** [comment] 2021-03-25 13:41
Followup - do you also have users with stock Chrome? Is the error ever present there? There might be some bugs in the Samsung fork only? How often is this happening, if you could estimate? Is the error relatively common, reproducible for those users?

**Comment by koto** [comment] 2021-03-25 13:59
FWIW, Chromium 83 is awfully old, there might have been a bug we never spotted and fixed by accident when doing some changes. 84, for example, had a lot of TT changes. Is there a newer version of the Samsung browser? Is the error present there?

**Comment by koto** [comment] 2021-03-25 14:17
I asked around (thanks @otherdaniel!), it's probably https://bugs.chromium.org/p/chromium/issues/detail?id=1101344, which was fixed in 86.

**Comment by jlowcs** [comment] 2021-03-25 14:19
We are using the latest version of DOMPurify (2.2.7).

Looking at the aggregation of reported errors, most of them have `Chrome/83.0.4103.106` in their user agent. There are a few `Chrome/79.0.3945.136` and `Chrome/75.0.3770.143`.

Here's a partial screenshot of the aggregation:
![image](https://user-images.githubusercontent.com/3777724/112488029-7fd49a00-8d7d-11eb-95f1-6269ce156cb4.png)

We have about 20-25 errors reported per day on the page using DOMPurify, out of around 3,000 daily visits of that page with a `SamsungBrowser` user agent, which is - I concede - a very small proportion of users (about 0.007%).

Looking at our stats, it also appears that most user agents containing `SamsungBrowser` also contain `Chrome/83.0.4103.106`. That makes sense looking at https://user-agents.net/browsers/samsung-browser/versions/13-2.

**Comment by jlowcs** [comment] 2021-03-25 14:22
> I asked around (thanks @otherdaniel!), it's probably https://bugs.chromium.org/p/chromium/issues/detail?id=1101344, which was fixed in 86.

Thanks for the link! Would you suggest we try to catch those errors and fall back to another behavior if an error is thrown? For now, we went with a simple HTML tag stripping fallback when DOMPurify is not supported.

**Comment by jlowcs** [comment] 2021-03-25 14:30
looks like SamsungBrowser 14 will use Chrome/87 and is currently in beta: https://medium.com/samsung-internet-dev/samsung-internet-releases-14-0-cf62d916193

**Comment by cure53** [comment] 2021-03-25 14:41
From our end, uncertain what best to be done. 

We could wrap the offensive line in a try-catch block and release - but is that the optimal way to go about this? Not a big fan of monkey patching the code for broken legacy browsers.

What would you suggest?

**Comment by cure53** [comment] 2021-03-25 14:47
That being said, I cannot get a clean repro either on BS. This makes it hard to produce a working fix.

**Comment by jlowcs** [comment] 2021-03-25 14:50
I agree that monkey patching the library would not be ideal. The best way to approach this might be to add a try-catch block in the app code instead.

We could also attempt a retry when an exception is thrown, since this behavior seems a bit random..

**Comment by cure53** [comment] 2021-03-25 14:54
Oki doki :)

**Comment by jlowcs** [comment] 2021-03-25 15:12
Thanks for investigating!

**Closed** 2021-03-28 11:03 UTC

**Comment by Slapbox** [comment] 2021-10-30 20:58
Still seeing this in `Electron@11.x`, which is based on a minimum Chromium version of `87.0.4280.47`. It's growing to be unbelievably disruptive to debugging. Any ideas?

**Comment by intellent** [comment] 2022-04-12 20:44
I’m experiencing this error in current Edge Version 100.0.1185.39 (Official build) (x86_64). I am getting reports on Chrome, as well. Firefox and Safari work fine.

**Comment by otherdaniel** [comment] 2022-04-13 12:50
> I’m experiencing this error in current Edge Version 100.0.1185.39 (Official build) (x86_64). I am getting reports on Chrome, as well. Firefox and Safari work fine.

Do you have an example that would reproduce this?

(I'm unaware of any recent changes in this particular area in Chromium, so this is surprising. I'll gladly investigate if I have a repro.)

**Comment by intellent** [comment] 2022-04-13 19:21
This is super strange. I use DOMPurify inside a `beforeprint` event listener. If I trigger the print dialog using the browser’s native function (Ctrl/Cmd+P), everything works. If I trigger the print dialog programmatically via `window.print()` the error above occurs.

Have no idea, what could cause the difference, but I’ll continue investigating.

**Comment by otherdaniel** [comment] 2022-04-14 10:05
> This is super strange. I use DOMPurify inside a `beforeprint` event listener. If I trigger the print dialog using the browser’s native function (Ctrl/Cmd+P), everything works. If I trigger the print dialog programmatically via `window.print()` the error above occurs.
> 
> Have no idea, what could cause the difference, but I’ll continue investigating.

This isn't as strange as it may seem, since the [original bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1101344)   had a root cause about [event handlers + printing](https://bugs.chromium.org/p/chromium/issues/detail?id=956832), too, with an observed difference between UI-initiated and script-initiated printing. I'm going to guess we have a regression somewhere in that space.

If you do have a repro, I'd be happy if you could open a bug on Chromium (https://crbug.com/new) and assign it to me ([owner of the previous bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1101344)).

(Background: In Chromium, printing "pauses" JS processing during some phases so that the printed image can be built up without interference. If the scope of the "pause" is inaccurate and the pause is still active when the browser intentionally runs JS, e.g. for running the printing event handlers, then JS callbacks (and various other things) will fail in mysterious ways, causing this error message. While of course it might be something different this time, your observation that it's about printing, and that it depends on the code path that triggers the printing, makes me rather suspicious.)

**Comment by intellent** [comment] 2022-04-14 10:54
Okay, that’s interesting, indeed.

> If you do have a repro, I'd be happy if you could open a bug on Chromium

I’m currently not able to distill the problem down to its bare bones. However, I could send you a link to a public project of mine. There, the error occurs in combination with DOMPurify. Would that help? How can I reach you personally to send you the URL?

**Comment by otherdaniel** [comment] 2022-04-14 12:51
> I’m currently not able to distill the problem down to its bare bones. However, I could send you a link to a public project of mine. There, the error occurs in combination with DOMPurify. Would that help? How can I reach you personally to send you the URL?

Yes, this is valuable, as long as it reproduces the problem.

I'm tracking this in https://crbug.com/1316315. You can add info there or email me at vogelheim@chromium.org, if you prefer. Please do let me know whether it's okay to pass the repro around, since I don't know the printing code and will need help from other developers.

**Comment by Techn1x** [comment] 2023-01-17 02:06
Hi @otherdaniel - I'd like to bring your attention to a thread in the Highcharts.js repo where this issue is discussed along with a handful of simple repro's demonstrating the print error.
https://github.com/highcharts/highcharts/issues/16931

We also came to the conclusion it's only when triggered programmatically (eg via `window.print()` ), and related to Trusted Types

Here's a jsfiddle where the error occurs via matchMedia('print')
http://jsfiddle.net/t0pn9c27/

Here's a jsfiddle where the error occurs in the beforePrint handler (note: it's wrapped in a try/catch, may want to remove that to see error in console)
https://jsfiddle.net/highcharts/4e91ka2q/

Happy to help out with this one to test out fixes etc.

**Comment by dstarosta** [comment] 2023-06-09 21:57
I have this problem after triggering the `window.print()` function (or Control-P) as well.

**Comment by Techn1x** [comment] 2024-11-29 06:14
For anyone listening on this thread, this is resolved in Highcharts v12
