### ISSUE TITLE
Typescript error when using factory function

### ISSUE THREAD

**Issue by bard** [cure53/DOMPurify#323] opened 2019-02-23 07:42 UTC
#### Input

index.ts:

```js
import createDOMPurify from 'dompurify'
const DOMPurify = createDOMPurify('<html/>')
```

#### Output

```shell
$ yarn run tsc
yarn run v1.13.0
warning package.json: No license field
$ /tmp/test/node_modules/.bin/tsc
index.ts:2:19 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/tmp/test/node_modules/@types/dompurify/index")' has no compatible call signatures.

2 const DOMPurify = createDOMPurify('<html/>')
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

#### Versions

```
$ node -v
v10.15.1
$ cat package.json
{
  "dependencies": {
    "@types/dompurify": "^0.0.32",
    "@types/jsdom": "^12.2.2",
    "dompurify": "^1.0.10",
    "typescript": "^3.3.3333"
  }
}
```

**Comment by tdeekens** [comment] 2019-02-23 08:02
The typings of DefinatelyTyped do not contain the factory function. See here 
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dompurify/index.d.ts. Moreover, the factory would not receice the html string but the global (window). So assuming what you intend to do you can just juse sanitize maybe?

**Comment by bard** [comment] 2019-02-23 09:45
Sorry, I wanted to show a minimal demonstration and ended up making an incorrect one. I have a DOM object and I'm using DOMPurify like this:

```js
import { JSDOM, VirtualConsole } from 'jsdom'
import createDOMPurify from 'dompurify'

const data = '<html><body></body></html>'
const url = 'http://example.com'

const virtualConsole = new VirtualConsole()
virtualConsole.sendTo(console, { omitJSDOMErrors: true })
const jsdom = new JSDOM(data, {
  url,
  virtualConsole
})

const DOMPurify = createDOMPurify(jsdom.window)
const purifiedHtmlElement = DOMPurify.sanitize(document.documentElement)
```

(Same error as above.)

It's still possible to compile by placing `// @ts-ignore` above the line that creates DOMPurify and giving up type checks for that objects.

I think that the lack of the factory function in the declarations means one cannot purify a DOM object instead of a string; doing so requires passing the `window` argument to the factory, but passing the `window` argument to the factory prevents compilation.

**Comment by tdeekens** [comment] 2019-02-23 10:46
Okay spinning up some CodeSandboxes as repro cases.

With normal JS: https://codesandbox.io/s/xv76kpq4lw

```js
import createPurify from "dompurify";

const purify = createPurify();

console.log(purify.sanitize("<img src=x onerror=alert(1)//>"));
```

Works for me.

With simple TS example (without JSDOM): https://codesandbox.io/s/16257o3x7

```js
import createPurify from "dompurify";

const purify = createPurify();

console.log(purify.sanitize("<img src=x onerror=alert(1)//>"));
```

Works for me.

With TS (copied your code): https://codesandbox.io/s/rrjppox48n

```js
import { JSDOM, VirtualConsole } from "jsdom";
import createDOMPurify from "dompurify";

const data = "<html><body></body></html>";
const url = "http://example.com";

const virtualConsole = new VirtualConsole();
virtualConsole.sendTo(console, { omitJSDOMErrors: true });
const jsdom = new JSDOM(data, {
  url,
  virtualConsole
});

const DOMPurify = createDOMPurify(jsdom.window);
console.log(DOMPurify.sanitize(data));
```

It works for me too. Note that I adapted your code slightly. You were passing in the `documentElement`.

```diff
-const purifiedHtmlElement = DOMPurify.sanitize(document.documentElement)
+console.log(DOMPurify.sanitize(data)) 
```

Sanitisation works, to my knowledge, on the string not the element itself. So to say within your example you could also

```diff
+console.log(DOMPurify.sanitize(document.documentElement.innerHTML))
```

I am not sure why you get the compilation error. At least I fail to reproduce it.

**Comment by bard** [comment] 2019-02-23 17:12
Passing in the `documentElement` was intentional as I have a DOM before purifying and I need a DOM afterward, so I'd rather have DOMPurify work on the DOM directly rather than perform extra serialization/deserialization. From the source it appears that passing in a node instead of a string is a supported use case:

https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L929

```js
  /**
   * Sanitize
   * Public method providing core sanitation functionality
   *
   * @param {String|Node} dirty string or DOM node
   * @param {Object} configuration object
   */
  // eslint-disable-next-line complexity
  DOMPurify.sanitize = function(dirty, cfg) {
```

I'm not sure why the codesandbox example doesn't trigger any errors, it might have to do with `@types/dompurify` missing from package.json or [parcel swallowing Typescript errors](https://github.com/parcel-bundler/parcel/issues/465).

Full repro (which I should have provided in the first place...):

```
$ git clone https://github.com/bard/dompurify-repro 
Cloning into 'dompurify-repro'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 7 (delta 0), reused 7 (delta 0), pack-reused 0
Unpacking objects: 100% (7/7), done.
$ cd dompurify-repro/
$ yarn install
yarn install v1.13.0
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

Done in 1.69s.

$ yarn run tsc
yarn run v1.13.0
warning package.json: No license field

$ /tmp/dompurify-repro/node_modules/.bin/tsc
index.ts:8:19 - error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("/tmp/dompurify-repro/node_modules/@types/dompurify/index")' has no compatible call signatures.

8 const DOMPurify = createDOMPurify(jsdom.window)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by tdeekens** [comment] 2019-02-23 17:59
> From the source it appears that passing in a node instead of a string is a supported

If so apologies for potentially inaccurate information. I am not a core contributor to the library. Also just a user and part time helper. 

> it might have todo with @types/dompurify

That is possible and what I meant initally. They are externally maintained and not contributed (to my knowledge) by library authors. Maybe you can see if debugging the types locally and opening a fix upstream can help. 

> maybe parcel swallows the error

I would rather say it has to do with the types which are not part of this repo. As a result, we can conpile with TS I do not stricly see the issue on this repo. 

Anyway, I feel a core contributor should also state their level of support towards commity types, if they are the issue, and how we (or you) can help to solve the issue there.

**Comment by bard** [comment] 2019-02-23 18:27
No worries, and thanks for looking into this! Before filing the issue I had tried refining the typings but came away empty-handed, I gave it another go now and it looks like it's working: https://gist.github.com/bard/cac1e1a11bdd1bb249b03a2874123007

I never wrote ambient declarations besides quick fixes so I'll test it for a while before contributing to DefinitelyTyped.

**Comment by cure53** [comment] 2019-02-25 08:31
Hey all, is there anything for us to do here?

**Comment by tdeekens** [comment] 2019-02-25 08:34
Status is that it seems that the type definitions for TypeScript at DefinatelyTyped are not accurate as the expression `const DOMPurify = createDOMPurify(jsdom.window)` won't compile due to errors. Without the types installed (at least at my repro case) everything seems fine.

It's a question of if anybody here wants to contribute back to `@types/dompurify` and fix things there.

**Comment by cure53** [comment] 2019-02-25 08:55
Ah okay, maybe @tomholub might be the right person to ping? 

See https://github.com/cure53/DOMPurify/issues/305

**Comment by cure53** [comment] 2019-03-05 14:28
Closing this now, likely not our bug. Please re-open if that was the wrong thing to do.

**Closed by cure53** 2019-03-05 14:28 UTC
