### ISSUE TITLE
Cannot read property 'fetch' of null

### ISSUE THREAD

**Issue by 7twin** [cure53/DOMPurify#375] opened 2019-11-02 03:41 UTC
### Background & Context

Filing this bug in the hopes that either somebody could come up with a minimal reproduction case [needed to file an issue with jsdom](https://raw.githubusercontent.com/jsdom/jsdom/master/.github/ISSUE_TEMPLATE.md) or with an issue inside domPurify.

Note that this can't be reproduced with jsdom as of my knowledge. I've tried all examples that triggered the fetch null exception before, but only can get it triggered if I pass that html to domPurify, not jsdom directly.

I fixed the issue for myself, by just applying my patch: https://github.com/jsdom/jsdom/pull/2510 via https://github.com/ds300/patch-package - but I'd want to help get this issue fixed at upstreams. (whichever of the upstreams causes the issue, though really, checking for a null could solve it all in jsdom... instead of new issues arising that cause the null fetch..)

### Versions

Node: v12.10.0
domPurify: 2.0.7
jsdom: 15.2.0

### Test Case

Very simple domPurify test case to trigger the exception:

```js
const createDOMPurify = require('dompurify');
const { JSDOM } = require('jsdom');

const window = (new JSDOM('')).window;
const DOMPurify = createDOMPurify(window);

let src = '<img src="https://test.com/test.png">';
console.log(DOMPurify.sanitize(src));
```

#### Input

`<img src="https://test.com/test.png">`

#### Given output

```
xxx/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:18
    const request = this._resourceLoader.fetch(url, {
                                         ^

TypeError: Cannot read property 'fetch' of null
    at PerDocumentResourceLoader.fetch (xxx/node_modules/jsdom/lib/jsdom/browser/resources/per-document-resource-loader.js:18:42)
    at HTMLImageElementImpl._attrModified (xxx/node_modules/jsdom/lib/jsdom/living/nodes/HTMLImageElement-impl.js:39:36)
    at Object.exports.appendAttribute (xxx/node_modules/jsdom/lib/jsdom/living/attributes.js:62:11)
    at Object.exports.setAttributeValue (xxx/node_modules/jsdom/lib/jsdom/living/attributes.js:218:13)
    at JSDOMParse5Adapter.adoptAttributes (xxx/node_modules/jsdom/lib/jsdom/browser/parser/html.js:152:18)
    at JSDOMParse5Adapter.createElement (xxx/node_modules/jsdom/lib/jsdom/browser/parser/html.js:73:10)
    at Parser._appendElement (xxx/node_modules/parse5/lib/parser/index.js:553:42)
    at areaStartTagInBody (xxx/node_modules/parse5/lib/parser/index.js:1519:7)
    at Object.startTagInBody [as START_TAG_TOKEN] (xxx/node_modules/parse5/lib/parser/index.js:1725:17)
    at Parser._processToken (xxx/node_modules/parse5/lib/parser/index.js:657:55)
```

**Comment by cure53** [comment] 2019-11-02 08:53
Interesting, but what can we do here?

**Comment by 7twin** [comment] 2019-11-02 11:50
@cure53 I was hoping you would be able to make a small minimal reproduction case for anybody to then file an issue on jsdom (they decline any third party examples) or to maybe determine why it comes to that issue in domPurify to begin with, e. g. how it processes the html given with jsdom and makes it fetch a null.

**Comment by cure53** [comment] 2019-11-02 14:08
Sorry, no. This seems to be out of scope for us. Please let me know if this is indeed our bug and I will reopen.

**Closed by cure53** 2019-11-02 14:08 UTC

**Comment by 7twin** [comment] 2019-11-02 14:53
@cure53 It is an issue with how domPurify modifies or tries to manipulate in some way the html given, because if you try to recreate the issue with the original html input, jsdom never crashes (as in the past filed issues), only if done through domPurify. 

All of this could be avoided if jsdom implemented null checks, but the goal of the project seems to be that everything that could cause a null are avoided instead of checking for the consequence.

That means third party packages like domPurify need to be debugged for how they cause that regression, to be able to fix it.

**Comment by 7twin** [comment] 2019-11-02 16:13
Found a way to trigger this issue with first party jsdom code and [submitted an issue](https://github.com/jsdom/jsdom/issues/2701), but until that is fixed, any html containing images with src is broken and crashes domPurify.

**Comment by cure53** [comment] 2019-11-02 16:42
Unless we learn how to work around this, we cannot do much right now. As far as I can see, the issue is not with our code but with the way jsdom creates documents.

**Comment by acemtp** [comment] 2019-12-02 10:12
Hey @cure53,

For information, jsdom fixed the issue, we just have to wait the release and dompurify update with the new release

https://github.com/jsdom/jsdom/issues/2701

**Comment by cure53** [comment] 2019-12-02 10:20
Thank you very much for the heads-up!

**Comment by acemtp** [comment] 2020-07-28 08:02
Hello @cure53

It seems that dompurify still use version 8.x.x of JSDOM and this bug is fixed in latest JSDOM, could you consider updating version of JSDOM?

Thank you very much
