### ISSUE TITLE
DOMPurify.sanitize converts numbers to strings

### ISSUE THREAD

**Issue by woudsma** [cure53/DOMPurify#491] opened 2020-11-26 23:12 UTC
### Background & Context

We plan to use `dompurify` in production but found out it broke handling of certain logic in our forms.
The `sanitize` function converts variables of type `number` to `string`. My mistake for not checking that.
I can see this library tries to do a single thing very well, but I felt this was worth mentioning as I didn't see an issue about this yet.

#### Input

```js
import { sanitize } from 'dompurify'

console.log(
  typeof sanitize(0.5),
  '\n',
  typeof 0.5,
)
```

#### Given output

```
string
number
```

#### Expected output

```
number
number
```

### Feature

An option to return the value as is, when the input type is not `string`.

But the next question would be, what if you pass an object / array into `sanitize`.
I'm not sure if you would want this library to deal with each edge case, simply assuming any input is a string is pretty safe.

**Comment by cure53** [comment] 2020-11-27 07:31
Heya, I think it might be making more sense to check for the type before handing things over to DOMPurify. There is lots of different types and we would have to implement check for all of them if we do so for number - thinking `RegExp`, `Date`, `Infinity`, `undefined`, etc etc.

Basically, if you want to sanitize you likely already know if the data you work with can contain user controlled data or risky HTML. In case of a number, sanitization should simply not be done - imho.

What do you think?

**Comment by cure53** [comment] 2020-12-02 16:19
Closing this for now, not a bug.

**Closed by cure53** 2020-12-02 16:19 UTC
