### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by yamafaktory** [cure53/DOMPurify#215] opened 2017-05-22 07:05 UTC
> This issue proposes a bug that occurs in latest Safari version (`Version 10.1.1 (12603.2.4)`).

### Background & Context

Latest version of DOMPurify (`v0.9.0`) is currently using a feature test which makes Safari throwing a CSP error.

#### Input

Not relevant regarding the issue.

#### Given output

Safari throws the following line in the console:

```sh
Refused to connect to data:text/html;charset=utf-8,%3Csvg%3E%3Cp%3E%3Cstyle%3E%3Cimg%20src=%22%3C/style%3E%3Cimg%20src=x%20onerror=alert(1)//%22%3E because it does not appear in the connect-src directive of the Content Security Policy.
```

This seems to be caused by the following line https://github.com/cure53/DOMPurify/blob/d91304b6aa24529521a34dfbe247369db23a8a88/src/purify.js#L463.

#### Expected output

Not relevant in this case.

Thanks for your great work!

**Comment by cure53** [comment] 2017-05-23 19:58
Hmmm, this is a tricky one, nice find! We'll have a look.

**Comment by cure53** [comment] 2017-05-23 20:11
I am wondering - is there any way to detect CSP without throwing a CSP error?

https://stackoverflow.com/a/19610169 < seems not but still researching.

**Comment by cure53** [comment] 2017-05-23 20:22
I was hoping we could maybe use an event handler. While the event triggers, the console warning still appears. I am not sure if this is fixable right now.

```javascript
document.addEventListener("securitypolicyviolation", function(e) {
    alert('block thread')
});
var payload = '<svg xmlns="http://www.w3.org/2000/svg"><g onload="javascript:alert(1)"></g></svg>';
document.createElement('body').innerHTML = payload;
```

**Comment by cure53** [comment] 2017-05-25 07:49
Okay, it seems we cannot really fix this - unless you have a fresh idea. Is it okay to close this?

**Comment by yamafaktory** [comment] 2017-05-25 13:13
Thanks a lot for the feedback 👍. I'll try to have a look at it later today. If it's going nowhere, feel free to close this issue.

**Comment by cure53** [comment] 2017-05-25 20:39
Thx :) Please re-open if there is any fresh ideas how to handle it. Right now, I think, infeasible.

**Comment by rnicholus** [comment] 2017-06-12 16:52
Can this be re-opened, since it's still an issue, one which may prevent 0.9.0 from being used in Safari?

**Comment by cure53** [comment] 2017-06-12 16:55
Sure :)

**Comment by cure53** [comment] 2017-06-13 07:58
> Can this be re-opened, since it's still an issue, one which may prevent 0.9.0 from being used in Safari?

@rnicholus So what's the plan now? Do you have any suggestions as to how to fix this issue?

**Comment by cure53** [comment] 2017-06-28 11:32
Closing for inactivity.

**Closed by cure53** 2017-06-28 11:32 UTC

**Comment by ajdumanhug** [comment] 2017-06-30 06:02
Hello World

**Comment by CaptainN** [comment] 2017-07-20 17:27
This bug prevents my entire app from loading in mobile Safari (it loads fine on macOS) - should it really be closed? Is there some workaround available?

**Comment by cure53** [comment] 2017-07-20 17:42
> This bug prevents my entire app from loading in mobile Safari 

But why? 

>  Is there some workaround available?

Well, if we have more info as to what's the problem here, we can potentially do something. So far this ticket was about CSP errors showing on the browser console. Which we eval'd as non-issue.

**Comment by CaptainN** [comment] 2017-07-20 17:51
Hmm, maybe it's something else keeping it from working on iOS - I assumed it was this, because it's the only error in my console.

**Comment by cure53** [comment] 2017-07-20 17:57
If it's us let us know - we will fix it with light-speed then! :)

**Comment by CaptainN** [comment] 2017-07-20 18:56
I can confirm it's dompurify. Here's my utility function:

```JavaScript
import DOMPurify from 'dompurify'

export default function reactDOMPurify (html) {
  // return {__html: html}
  return {__html: DOMPurify.sanitize(html, {ADD_TAGS: ['iframe']})}
}
```

If I comment out the import, and return an unfiltered react html object, everything works. If I use dompurify, I get a blank screen.

**Comment by CaptainN** [comment] 2017-07-20 18:57
I even get a blank screen just from importing dompurify

```JavaScript
import DOMPurify from 'dompurify'

export default function reactDOMPurify (html) {
  return {__html: html}
  //return {__html: DOMPurify.sanitize(html, {ADD_TAGS: ['iframe']})}
}
```

**Comment by cure53** [comment] 2017-07-20 19:00
Any error messages?

**Comment by yamafaktory** [comment] 2017-07-20 19:06
I can confirm that the issue is a breaking one. In our propertiary app, we can't update to the latest dompurify version (see initial issue's error message).

**Comment by cure53** [comment] 2017-07-20 19:14
So, it's definitely the line you highlighted earlier? At that point, the Safari tests are done and it should be safe to just try/catch this.

Can you try locally? I cannot repro the error thus have trouble to debug.

**Comment by CaptainN** [comment] 2017-07-20 19:19
The only error message I get is the one above. It's weird that I get that same error message in the macOS version of Safari, but it doesn't halt execution like it does on iOS.

**Comment by cure53** [comment] 2017-07-20 19:32
Check the most recent commit, maybe that fixes it?

**Comment by CaptainN** [comment] 2017-07-20 20:11
In my initial testing it does fix the problem.

It still outputs the error to the console, but it no longer halts execution.

**Comment by cure53** [comment] 2017-07-21 16:02
So, all fine now @yamafaktory @CaptainN @rnicholus ? :)
