### ISSUE TITLE
Issue with sanitizing the SVG tags (<text>, <tspan>,...)

### ISSUE THREAD

**Issue by anksanu** [cure53/DOMPurify#734] opened 2022-11-16 01:03 UTC
> This issue proposes a [bug, feature] which...

### Background & Context

`dompurify.sanitize(....)`  **v2.4.0** is removing SVG tags (`<text>, <tspan>`) during sanitization.

The bug is not present in **v2.0.3**

#### Input
```js
dompurify.sanitize(<below html as string>);
```

```html
<svg xmlns="http://www.w3.org/2000/svg">
    <path d="M 5 10 A 5 5 0 1 1 5.00499999916667 9.999997500000209 Z"
      class="foo-color-0"></path>
  </svg>
  <text x="21" text-anchor="start" y="17" aria-hidden="true">
     <tspan title="foo 1">foo 1</tspan>
  </text>
```

##### **v2.0.3**
```html
<svg xmlns="http://www.w3.org/2000/svg">
    <path d="M 5 10 A 5 5 0 1 1 5.00499999916667 9.999997500000209 Z"
      class="foo-color-0"></path>
</svg>
<text x="21" text-anchor="start" y="17" aria-hidden="true">
   <tspan title="foo 1">foo 1</tspan>
</text>
```

##### **v2.4.0**
```html
<svg xmlns="http://www.w3.org/2000/svg">
  <path d="M 5 10 A 5 5 0 1 1 5.00499999916667 9.999997500000209 Z"
    class="foo-color-0"></path>
</svg>
```

#### Expected output
```html
<svg xmlns="http://www.w3.org/2000/svg">
  <path d="M 5 10 A 5 5 0 1 1 5.00499999916667 9.999997500000209 Z"
    class="foo-color-0"></path>
</svg>
<text x="21" text-anchor="start" y="17" aria-hidden="true">
   <tspan title="foo 1">foo 1</tspan>
</text>
```

### Feature
v2.4.0 should be compatible with v2.0.3

**Comment by cure53** [comment] 2022-11-16 07:17
Not a bug as far as I can see - the `<text>` is outside the SVG which is invalid :)

I think, if you change the whole document namespace to SVG via DOMPurify config, it should work again.

**Comment by mmarekbb** [comment] 2022-11-16 10:32
We're having the same problem. Setting `NAMESPACE: 'http://www.w3.org/2000/svg'` does not help.

This is a breaking change and should be marked as such - for now we're downgrading back to 2.2.3. This appears to have been introduced in 2.2.4.

**Comment by cure53** [comment] 2022-11-16 11:16
Not a bug, not a breaking change. 

You are feeding the sanitizer invalid and broken XML with a text node outside the root node.

If you look closely at the results, i.e. by writing the SVG you provide into an actual DOM, you will see that the `<text>` element is not a HTML node, no longer SVG. This is most likely not expected behavior.

**Comment by cure53** [comment] 2022-11-16 11:18
Note: they key problem here is that the `<text>` node is outside the SVG and therefore either a) non-wellformed SVG/XML _or_ b) it will become a node inside the HTML namespace. Both of which is likely not desired by your use-case, I presume.

**Comment by cure53** [comment] 2022-11-16 11:22
That being said, if you really want to do it like that _or_ have no other choice, you can still make it happen with this solution:

```javascript
var dirty = `<svg xmlns="http://www.w3.org/2000/svg">
    <path d="M 5 10 A 5 5 0 1 1 5.00499999916667 9.999997500000209 Z"
      class="foo-color-0"></path>
  </svg>
  <text x="21" text-anchor="start" y="17" aria-hidden="true">
     <tspan title="foo 1">foo 1</tspan>
  </text>`;

DOMPurify.sanitize(dirty, {PARSER_MEDIA_TYPE: 'image/xml+svg', NAMESPACE: 'http://www.w3.org/2000/svg' });
```

The result will be:

```xml
<svg xmlns=\"http://www.w3.org/2000/svg\">
    <path class=\"foo-color-0\" d=\"M 5 10 A 5 5 0 1 1 5.00499999916667 9.999997500000209 Z\"/>
  </svg>
  <text xmlns=\"http://www.w3.org/2000/svg\" aria-hidden=\"true\" y=\"17\" text-anchor=\"start\" x=\"21\">
     <tspan title=\"foo 1\">foo 1</tspan>
  </text>
```

Note that the dangling `<text>` element will correctly be given a namespace to make sure it is parsed as SVG and not HTML or anything else.

**Comment by cure53** [comment] 2022-11-17 12:43
Closing this for now as the issue seems to be solved.

**Closed by cure53** 2022-11-17 12:43 UTC
