### ISSUE TITLE
Cannot prevent automatic conversion of phone numbers to <a links with tel: href

### ISSUE THREAD

**Issue by myufa** [cure53/DOMPurify#816] opened 2023-06-09 19:17 UTC
> This issue proposes a bug in dompurify ^2.3.3 on IOS 16

### Background & Context
When using dompurify on IOS 16 (and potentially other IOS versions) strings of numbers and dashes formatted as seen below are converted to telephone links. This is not to be confused with any formatting apple could be doing on these strings. The link is generated in the sanitize function. 

This is causing item IDs for our product to be misrepresented in the UI as phone numbers

This does not happen on desktop, that I have seen

#### Input

```javascript
sanitize("1234-567-891")
```

#### Given output

```
"<a href="tel:1234-567-891">1234-567-891</a>"
```

#### Expected output

```
"1234-567-891"
```

**Comment by cure53** [comment] 2023-06-12 12:17
Hah, interesting and seemingly a weird behavior of iOS and nothing we can fix. Unless you have any ideas?

**Comment by myufa** [comment] 2023-06-12 13:27
> Hah, interesting and seemingly a weird behavior of iOS and nothing we can fix. Unless you have any ideas?

This is not just an IOS behavior, these strings do not get formatted into links outside of the sanitize function.

**Comment by cure53** [comment] 2023-06-12 13:31
Well, we don't have any code implementing that, that I can pretty much guarantee :smile: So, where does this come from?

**Comment by cure53** [comment] 2023-06-12 13:36
I also tried this snippet on iOS v16 using BrowserStack: https://jsfiddle.net/0rcaLfe4/
It does not reproduce for me.

```
iPhone 14 v16.4

OS: iOS, v16.4
Browser: Safari
```

**Comment by cure53** [comment] 2023-06-15 09:56
Closing this for now, no repro, no case - please reopen if needed.

**Closed** 2023-06-24 11:27 UTC

**Comment by Anderman** [comment] 2023-12-29 17:25
I see this behaviour also on the IPhone. and it is indeed dompurify that adding this. That is because they use the virtual dom of safari which is inserting the phone number

 see where the confusion is coming from. DOMPurify uses a virtual DOM to sanitize HTML, but it doesn't inherently add links to numbers. It's designed to remove potentially harmful elements from HTML, not add new ones.

However, when DOMPurify parses and sanitizes the HTML, it uses the browser's HTML parsing engine, which in Safari on iOS includes automatic phone number detection. So, when the sanitized HTML is inserted back into the page, any phone numbers may appear as links, even though DOMPurify didn't explicitly add those links.

This is a feature of the browser, not DOMPurify. If you want to prevent this behavior, you can use the format-detection meta tag in your HTML:

`<meta name="format-detection" content="telephone=no"> `

This will tell Safari not to automatically detect and link phone numbers.
