### ISSUE TITLE
Casting tags to string rather than deleting ? 

### ISSUE THREAD

**Issue by AliD201** [cure53/DOMPurify#493] opened 2020-12-03 09:18 UTC
> This is a question about if something is possible 

### Background & Context

want to sanitize the incoming html to keep `<span>` and "`class`" but also to convert all other tags to text rather than deleting them, is that possible ? 

#### Input

input 1 : `This <span className="red">is a</span> demonstration.`
input 2 : `This <b>is a</b> demonstration.`

#### Expected output
output 1 but apply the class
output 1 : `This is a demonstration.`
output 2 convert to text   
input 2 : `This <b>is a</b> demonstration.`

**Comment by cure53** [comment] 2020-12-03 09:22
You should be able to do that with a hook, if I understand the question correctly.

**Comment by AliD201** [comment] 2020-12-03 09:49
can you help me maybe with a simple example ? 
I am not sure on how to use hooks on that part.
like maybe I need to look for all text within `<>` and somehow force it to be text before passing it to the sanitizer ?

**Comment by cure53** [comment] 2020-12-03 11:49
Yup, exactly. You'd probably wanna go with the `uponSanitizeElement` hook - examples can be found here and in the other files in the _demos_ folder: https://github.com/cure53/DOMPurify/blob/main/demos/hooks-demo.html

**Comment by AliD201** [comment] 2020-12-03 12:51
I tried to make each `<` a text node but  it prints as `[OBJECT TEXT]`
I know now we are kinda out of the scope of library discussion, but how may I cast it to text here ? 

i kept the uppercase just to make sure it is working since it only update or "sanitize" when there is a "<" 
```js
 DOMPurify.addHook("uponSanitizeElement", function (node, data) {
          // Set text node content to uppercase
          console.log(node.textContent);

          if (node.nodeName && node.nodeName === "#text") {
            
            let textnode = document.createTextNode("<")

            node.textContent = node.textContent.replace("<",textnode)
            node.textContent = node.textContent.toUpperCase();
          }
        });

        let changeTo = DOMPurify.sanitize(event.target.value
          , {
          ALLOWED_TAGS: ["span"],
          ALLOWED_ATTR: ["class"]
        }
        )
        setorValue({__html: changeTo})
    }
```

**Comment by cure53** [comment] 2020-12-03 14:39
Why not just use HTML entities instead? You can grab `innerHTML` and turn "<" into "&lt;"

**Comment by cure53** [comment] 2020-12-07 11:37
Closing this as not a bug

**Closed by cure53** 2020-12-07 11:37 UTC
