### ISSUE TITLE
_initDocument - Invalid calling object

### ISSUE THREAD

**Issue by franmico** [cure53/DOMPurify#159] opened 2016-05-23 15:32 UTC
Hi all,

I'm using the latest version of DomPurify library in some of my custom visualforce pages (Salesforce) and I'm facing an strange behaviour when using IE (10.0.9200.17028).

If I go to the demo page you have available using the same browser it works but as soon as use it in my visualforce page my JS breaks and I receive the exception Invalid calling object. The line where it breaks is 377 (getElementsByTagName). This occurs because the DOMParser is undefined in my visualforce page when using the IE version mention above, but instead of returning null it returns the object with empty values (img_1.jpg).

I have updated in my version line 365 from if (!doc) { to if (!doc || doc.body == undefined) and now it works.

Hope this is usefull

Cheers,
Fran.

![img_1](https://cloud.githubusercontent.com/assets/4990323/15475797/ba2cc52e-2103-11e6-8bf7-b23b93d8b30c.png)

**Comment by cure53** [comment] 2016-05-23 16:26
Heya!

> This occurs because the DOMParser is undefined in my visualforce page when using the IE version mention above, but instead of returning null it returns the object with empty values

Oh, why is that the case?

**Comment by cure53** [comment] 2016-05-23 16:30
We can probably easily fix that with another check in the method that builds the document - by simply checking if `documentElement` exists. But it would be good to identify the  root cause first before we add some code to the core.

**Comment by cure53** [comment] 2016-05-23 16:33
We would basically patch here:
https://github.com/cure53/DOMPurify/blob/master/src/purify.js#L365

And add another check like this:
`if (!doc || !doc.documentElement) {`

But let's find out first what is going on :)

**Comment by cure53** [comment] 2016-05-23 18:28
Maybe this branch works for you? Tests are all green so far.

https://github.com/cure53/DOMPurify/tree/IE10DOMParser

**Comment by franmico** [comment] 2016-05-23 19:50
Hi cure53!

Thank you very much for you rapid response  - the fix you added works perfectly  :)

I'm going to investigate the behaviour of the DOMParse in my visualforce page to give you a bit more details and try to find out the root of the problem

cheers,
Fran

**Comment by cure53** [comment] 2016-05-23 19:54
Cool, thanks :) We're close to the next release, this patch will be part of it then.

**Closed** 2016-05-23 20:14 UTC

**Comment by franmico** [comment] 2016-05-23 20:30
awesome! Thanks very much :)
