### ISSUE TITLE
Uncaught ReferenceError: c is not defined

### ISSUE THREAD

**Issue by ruvlol** [cure53/DOMPurify#391] opened 2020-02-13 12:16 UTC
### Background & Context

uncaught reference when html comment goes right after <a> tag

#### Input

```
DOMPurify.sanitize(`<a href="somelink" class="external-link" rel="nofollow">customtext</a><!-- qwe -->`)
```

#### Given output

![image](https://user-images.githubusercontent.com/31368712/74434534-ae422f00-4e73-11ea-929b-21068e1ea067.png)

console error: Uncaught ReferenceError: c is not defined

#### Expected output

sanitized html

**Comment by cure53** [comment] 2020-02-13 13:06
Heya, I have trouble reproducing. What browser is affected, what version are you using? 

Can you check with an uncompressed version so we know what `c` actually refers to?

**Comment by ruvlol** [comment] 2020-02-13 13:22
I used dist/purify.min.js in latest Chrome, now replaced it with dist/purify.js and it fixed the problem.

**Comment by cure53** [comment] 2020-02-13 13:24
So, does the minified version still have the problem? Or can we close the issue?

**Comment by ruvlol** [comment] 2020-02-13 13:27
I guess if there is no one else with the same problem, we can close that

**Comment by cure53** [comment] 2020-02-13 13:40
Just to be on the safe side, I tested with the latest compressed version on latest Chrome: 
No exceptions thrown. LGTM.

**Closed by cure53** 2020-02-13 13:40 UTC

**Comment by cawabunga** [comment] 2020-04-13 20:19
I faced a similar issue. 

My investigation came to variables naming collision after transpilation with Babel, or rather transpilation with enabled `babel-plugin-transform-react-remove-prop-types@0.4.24`. 

The problematic function was `_typeof` (not sure where it comes from). I tried to reproduce the bug without `DOMPurify` with just an ordinary javascript, but got no success. 

I solve my problem by importing ES-bundled version  instead of UMD-bundled. Actually I left the code as it is, because then there will be a problem with Jest since it prefers CJS-modules, so I changed the configuration of Webpack:
```
...
resolve: {
  alias: {
    // Prevents variable naming collision after babel transformation in production
    dompurify: 'dompurify/dist/purify.es',
  },
},
...
```
Hope it will help to somebody!
