### ISSUE TITLE
Crashes on IE11 if sanitizing a space

### ISSUE THREAD

**Issue by sontek** [cure53/DOMPurify#372] opened 2019-10-18 17:47 UTC
On IE11:

```
DOMPurify.sanitize(" ", {USE_PROFILES: {html: true}})
Unable to get property 'insertBefore' of undefined or null reference
```

Using latest version (2.0.6), you can verify it on:

https://cure53.de/purify

by opening the console and pasting the line of code above.

**Comment by cure53** [comment] 2019-10-19 10:29
Oh, nice spot! We will release 2.0.7 soon and the bug will be fixed

**Comment by peterblazejewicz** [comment] 2019-10-21 09:49
@sontek 
This can be closed, as the 2.0.7 was released (and one of the product I work with uses IE11, so I've checked this thread).
Thanks!

**Comment by peterblazejewicz** [comment] 2019-10-21 09:52
Hm,
so the '2.0.7' is not released via NPM yet? 
The online version states '2.0.7' as the `DOMPurify.version`

**Comment by cure53** [comment] 2019-10-21 09:53
Will be released very very soon :)

**Comment by cure53** [comment] 2019-10-21 09:53
Pretty much on it right now

**Comment by cure53** [comment] 2019-10-21 10:16
Alright, this fix should address the problem you described:

https://github.com/cure53/DOMPurify/commit/56b9e9caa85ee61664c86ba16306681ed9d6dbb0

Does it work as intended?

**Closed** 2019-10-21 12:24 UTC
