### ISSUE TITLE
DOMPurify.sanitize using TrustedTypes crashes Chrome 72

### ISSUE THREAD

**Issue by mmso** [cure53/DOMPurify#319] opened 2019-02-07 09:37 UTC
This issue proposes a bug which when using `DOMPurify.sanitize` with chrome://flags/#enable-experimental-web-platform-features enabled in Chrome 72 crashes the browser.

![trusted-types](https://user-images.githubusercontent.com/352607/52402322-47ea3a00-2ac4-11e9-894a-a2a3275abc1a.gif)

Note: This is probably a browser bug in Chrome, but I am reporting it here to let other people using this library know about it.

**Comment by cure53** [comment] 2019-02-07 09:41
Oh, that is likely very interesting for @koto :D

**Comment by koto** [comment] 2019-02-07 10:11
Do you have a repro case?

**Comment by mmso** [comment] 2019-02-07 10:14
@koto yes you can go to https://cure53.de/purify on Chrome 72 with the flag chrome://flags/#enable-experimental-web-platform-features enabled and hit the Sanitize button.

**Comment by koto** [comment] 2019-02-07 10:30
Thanks, looking into it in http://crbug.com/929601.

**Comment by koto** [comment] 2019-02-07 16:14
Update: we found the root cause and are fixing the bug in Chrome. There's a workaround:

```
 --enable-features=BlinkHeapUnifiedGarbageCollection
```

**Comment by cure53** [comment] 2019-02-09 12:01
Closing this - not our bug and now properly tracked.

**Closed by cure53** 2019-02-09 12:01 UTC
