### ISSUE TITLE
Chrome 77: sanitize() returns TrustedHTML-Object instead of string

### ISSUE THREAD

**Issue by Uzlopak** [cure53/DOMPurify#361] opened 2019-09-11 10:29 UTC
In our usecase Chrome77 breaks our code. The sanitize method returns TrustedHTML instead of a string. We fixed it by adding a .toString() to the result of sanitize().

#### Input

console.log(dompurify.sanitize("a"))

#### Given output
TrustedHTML-Object;

#### Expected output

"a"

**Comment by abduwaly** [comment] 2019-09-11 11:32
Hi @Uzlopak !
We encountered with the same issue as well and found that `.toString()` will fix this issue.

```
dompurify.sanitize("a").toString()
```

**Comment by cure53** [comment] 2019-09-11 11:51
Hey all, thanks for the report. This is intended behavior however when working with Trusted Types.

See here: https://github.com/cure53/DOMPurify#what-about-dompurify-and-trusted-types

@koto Maybe we should update the docs, is this on by default now?

**Comment by Uzlopak** [comment] 2019-09-11 12:02
@cure53 
@koto 
Maybe also fix @types/DOMPurify?

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/dompurify/index.d.ts

**Comment by mayrbenjamin92** [comment] 2019-09-11 12:11
I am still a bit confused about what has changed in Chrome 77? Did they change something related to the trusted API? Does anybody have a link to the changelog in Chrome were this was introduced?

**Comment by cure53** [comment] 2019-09-11 12:12
This is something @koto is likely to be able to answer

**Comment by marcneander** [comment] 2019-09-11 12:58
This change in API is risky. I fear a bunch of apps are now experiencing issues with this.

**Comment by abduwaly** [comment] 2019-09-11 13:00
<img width="1067" alt="Screen Shot 2019-09-11 at 8 56 10 PM" src="https://user-images.githubusercontent.com/26398225/64699109-af42ef00-d4d6-11e9-965d-37d8bad80fb1.png">
This is why it crashed on Chrome 77. It's an experimental API and it's been here from chrome 73 - 76 (but need users to manually enable it). But from Chrome 77, it's *Enabled* by default.
see : https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/trusted-types
@mayrbenjamin92

**Comment by cure53** [comment] 2019-09-11 13:44
The README file has been updated to reflect the changes in Chrome's behavior/config.
A PR has been sent to DefinitelyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/38298

Hope that clarifies things a bit.

**Comment by mayrbenjamin92** [comment] 2019-09-11 14:40
Thank you guys!

**Comment by koto** [comment] 2019-09-11 18:31
Trusted Types should not be enabled by default on Chrome 77. We're investigating what happened in https://bugs.chromium.org/p/chromium/issues/detail?id=1002685

**Comment by trymoto** [comment] 2019-09-11 20:43
In May i saw https://github.com/cure53/DOMPurify/issues/316
because our website broke under experimental flag
- "Oh, well, there will be major version and all of this good stuff before this whole TrustedHTML thingie ships to stable" :)
Today we saw it breaking a lot of production though.

IMHO it's a broken versioning and we're left with:
1) Wait for Chrome folks to fix 77 and do nothing until it happens again
2) Rely on people to hot-fix their own feature-detection / duck-typing / toString stuff in upcoming days when v77 adoption rate will go to the moon
3) Do a minor bump and save people

What do you think?

**Comment by cure53** [comment] 2019-09-12 06:11
@trymoto @koto I honestly understand both viewpoints here and the fact that things break in production is sub-optimal to say the least.

I am wondering what DOMPurify could do to fix things? Is there anything constructive we can do right now?

**Comment by Uzlopak** [comment] 2019-09-12 06:53
activating TrustedHTML by parameter instead of Feature detection would be a solution but you would need to release a new major as it is a breaking change.

But that would fix it perfectly.

**Comment by koto** [comment] 2019-09-13 08:16
I think we might also need a bugfix release that removes the TT as a return value from 1.x.x? Since this was the one that introduced a breaking change. I don't see branches in your repo, would that be a manual code change & release?

**Comment by cure53** [comment] 2019-09-13 10:19
No need for that, we will not start maintain different branches or bug-fix releases because of this rather small issue. 

I would go as far as to close this issue for now. As far as I can see, the tests are green, the offending feature has been placed behind a flag and the library behaves again as expected.

**Closed by cure53** 2019-09-13 10:19 UTC
